// Frozen snapshot-shaped data so App tests don't depend on which pools NYC
// Parks happens to have closed on any given scrape. The tests pin the clock
// to Monday 2026-08-31 10:00, so "Today" sessions below say Monday.
export const FIXTURE_POOLS = [
  {
    borough: 'Manhattan',
    pool_name: 'Chelsea Pool',
    pool_code: 'M260',
    status: 'open',
    location: {
      address: '430 West 25th Street',
      cross_streets: '9th & 10th avenues',
      city: 'New York',
      state: 'NY',
      zip_code: '10001',
      building_hours: {
        Monday_Friday: '7:00 AM - 8:00 PM',
        Saturday: '8:00 AM - 4:00 PM',
        Sunday: '8:00 AM - 2:00 PM',
      },
    },
    phone: '(212) 255-3705',
    url: 'https://www.nycgovparks.org/parks/M260/facilities/indoor-pools',
    membership_required: true,
    notes: null,
    reduced_hours: false,
    notice_links: [],
    closure_reason: null,
    closed_through: null,
    reopens: null,
    schedules: [
      { session_type: 'Lap Swim', days: 'Monday', time: '11:00 a - 1:00 p', date: '2026-08-31' },
      { session_type: 'Open Swim', days: 'Tuesday', time: '2:00 p - 4:00 p', date: '2026-09-01' },
    ],
    schedule_weeks: [],
  },
  {
    borough: 'Manhattan',
    pool_name: 'Hansborough Pool',
    pool_code: 'M131',
    status: 'closed',
    location: {
      address: '35 West 134th Street',
      cross_streets: 'Lenox Terrace Place between Lenox & 5th avenues.',
      city: 'New York',
      state: 'NY',
      zip_code: '10037',
      building_hours: {
        Monday_Friday: '6:00 AM - 10:00 PM',
        Saturday: '8:00 AM - 8:00 PM',
        Sunday: '8:00 AM - 6:00 PM',
      },
    },
    phone: '(212) 234-9603',
    url: 'https://www.nycgovparks.org/parks/M131/facilities/indoor-pools',
    membership_required: true,
    notes: 'Hansborough Recreation Center is closed for reconstruction.',
    reduced_hours: false,
    notice_links: [],
    closure_reason: 'for reconstruction',
    closed_through: null,
    reopens: null,
    schedules: [],
    schedule_weeks: [],
  },
  {
    borough: 'Brooklyn',
    pool_name: "St. John's Pool",
    pool_code: 'B245',
    status: 'open',
    location: {
      address: '1251 Prospect Place',
      cross_streets: 'Between Troy and Schenectady Avenues',
      city: 'Brooklyn',
      state: 'NY',
      zip_code: '11213',
      building_hours: {
        Monday_Friday: '6:00 AM - 10:45 PM',
        Saturday: '8:00 AM - 11:45 PM',
        Sunday: '8:00 AM - 5:45 PM',
      },
    },
    phone: '(718) 771-2787',
    url: 'https://www.nycgovparks.org/parks/B245/facilities/indoor-pools',
    membership_required: true,
    notes: null,
    reduced_hours: false,
    notice_links: [],
    closure_reason: null,
    closed_through: null,
    reopens: null,
    schedules: [
      { session_type: 'Lap Swim', days: 'Monday', time: '12:15 p - 1:45 p', date: '2026-08-31' },
      { session_type: 'General Swim', days: 'Tuesday', time: '11:00 a - 12:00 p', date: '2026-09-01' },
    ],
    schedule_weeks: [],
  },
];

export const FIXTURE_META = { updated_at: '2026-08-31T10:00:00Z', pool_count: FIXTURE_POOLS.length };
